version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
      - MYSQL_DATABASE=db_migrations_testing
    volumes:
      - "db_migrations_testing:/var/lib/mysql"
    ports:
      - "3306:3306"

volumes:
  db_migrations_testing:
